<script type="module">
  // Import the functions you need from the SDKs you need
  import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
  import { getAnalytics } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-analytics.js";
  // TODO: Add SDKs for Firebase products that you want to use
  // https://firebase.google.com/docs/web/setup#available-libraries

  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  const firebaseConfig = {
    apiKey: "AIzaSyDnor1tHuwttfCW_Skt21Iwwd5gqom-eyI",
    authDomain: "study-e0d2b.firebaseapp.com",
    projectId: "study-e0d2b",
    storageBucket: "study-e0d2b.firebasestorage.app",
    messagingSenderId: "206543223080",
    appId: "1:206543223080:web:c1278afdb1c0c37bce381d",
    measurementId: "G-JK26ZGELMG"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);
</script>
